trigger: 
  - main

pool:
  vmimage: ubuntu-latest
  
variables:
  buildconfiguration: 'Release'

steps:
  - script: dotnot build --configuration $(buildconfiguration)
  displayname: 'dotnet build $(buildocnfiguration)'